server:
  port: 9090
spring:
  application:
    name: yatakeout
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/yatakeout?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
mybatis-plus:
  configuration:
    #开启驼峰命名法，在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射，如address_book----->  AddressBook
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      配置数据库主键的生成策略
      id-type: ASSIGN_ID
yatakeout:
# 文件上传的保存目录
  path: D:\MyITData\JavaIDEA\JavaProject\yatakeout\img\